import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { AuthProvider } from "./contexts/AuthContext";
import { SessionProvider } from "./contexts/SessionContext";
import Navbar from "./components/Navbar";
import Dock from "./components/Dock";
import { SidebarDemo } from "./components/SidebarDemo";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Chronix",
    description: "Generated by rohitghosh1763",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased font-['Helvetica',Arial,sans-serif]`}
            >
                <ThemeProvider>
                    <AuthProvider>
                        <SessionProvider>
                            <SidebarDemo>
                                <div className="min-h-screen bg-[#f9f9f9] dark:bg-[#0f172a]">
                                    <Navbar />
                                    {children}
                                    <Dock />
                                </div>
                            </SidebarDemo>
                        </SessionProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
